language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ccaN0MK/xz1k5zug+MT2okD11sTJSU5oL3B2Qqqc9UCjnLhzCzLOHu1GzaA7B5fZ//qiiIsmRlh581L6T/IYhLfZjcTMVe3YCd3ZjP7IyT95KjiNRDqCsTCOUOLVNBhcGB3yCuTUwlBGpfJmBQ9CL3GvaMKz5xFEvXRlfp3ndq3splV6GmsGR6lat84o+GA1R/y/2CSvfbZb/m9clrRjjl43DlFyzLzahQYTRimhFBgazD7BvxvLcy76KhklWJ/+IpEO2TnKoSdyhmp/DOKBYTqc/eCnODlLQNeibU3WJ3ZfLylcGF+llWptfoXVMblHRsnQZ3cWaYr9BvLrsHlR3aWzSeDZjgRF18eB2mP4lZBsk7ujpbALlH0KqYewY0ApFgrT9PikquQR0zcGVq3A14IpFpGaxsfcO2gxheiz5i77dnelkBBPuxTbF9B8wJ3BIbH3jHGj+wIpOmgnINOFY6oVuivU7f+abofS1zJM7AKBITC3yFFhQ/1x0txiQBIHh46VIZqsWIrz9mHh2SD5dkV8ch67d9+vmaG9IlIrNh0ADITHl67635DHnnp+mWhZZEyz6OegwIcqqW6rPpFwgcaY1bGR1E6ys4YK7SDT/yUe4SH33tU64+krv6BKCtM1jjaaT0g1g26l+MP9Df7c8Dey1OO80NUCy6htjhvnRKc=
  app: trivia-gamemaster
  skip_cleanup: true
